spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.data.redis.host=${SPRING_DATA_REDIS_HOST:redis}

spring.jpa.hibernate.ddl-auto=validate
spring.main.banner-mode=off
spring.flyway.enabled=true
qrvet.cookie-secure=${QRVET_COOKIE_SECURE:true}
