spring.jpa.hibernate.ddl-auto=validate
spring.main.banner-mode=off
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.data.redis.host=${REDIS_HOST:redis}
spring.mail.host=${MAIL_HOST}
qrvet.cookie-secure=${COOKIE_SECURE:false}